services:
  app:
    build:
      context: ./app
      dockerfile: ../dockerfile
    container_name: nextjs_app
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/.next
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
